name: MVLobby
version: '1.0'
main: dev.mv.lobby.Lobby
api-version: '1.20'
depend: [
  'MVPtk'
]
authors: [
  'Maxim Savenkov',
  'Julian Hohenhausen'
]
commands:
  lobby:
    description: 'Return to the lobby'
  party:
    description: 'Party commands'
    aliases: ['p']
  chat:
    description: 'Choose default chat'
  pchat:
    description: 'Speak in party chat'
    aliases: ['pc']
  achat:
    description: 'Speak in all chat'
    aliases: ['ac', 'all']